# Generated by Django 4.1.3 on 2022-12-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('apellido_pat', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_mat', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('correo_e', models.CharField(max_length=50, verbose_name='Correo electrónico')),
                ('celular', models.CharField(max_length=15, verbose_name='Numero celular')),
            ],
        ),
    ]
