# Generated by Django 4.1.4 on 2022-12-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleado_area_alter_empleado_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'ADMINISTRACION Y FINANZAS'), (3, 'COMERCIAL')], null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Numero celular'),
        ),
    ]
