# Generated by Django 4.1.4 on 2022-12-28 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('empleados', '0006_empleado_status_alter_empleado_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='status',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.ForeignKey(blank=True, choices=[(2, 'ADMINISTRACION Y FINANZAS'), (3, 'COMERCIAL')], null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.area'),
        ),
    ]
